# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tflite_dynamic.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='tflite_dynamic.proto',
  package='tflite_dynamic',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=b'\n\x14tflite_dynamic.proto\x12\x0etflite_dynamic\"\xd4\x01\n\rTfliteRequest\x12\x39\n\x0buploadModel\x18\x01 \x01(\x0b\x32\".tflite_dynamic.UploadModelRequestH\x00\x12\x35\n\tinference\x18\x02 \x01(\x0b\x32 .tflite_dynamic.InferenceRequestH\x00\x12?\n\x0egetModelFormat\x18\x03 \x01(\x0b\x32%.tflite_dynamic.GetModelFormatRequestH\x00\x42\x10\n\x0etflite_request\"\xec\x01\n\x0eTfliteResponse\x12\x11\n\x07\x66\x61ilure\x18\x01 \x01(\tH\x00\x12:\n\x0buploadModel\x18\x02 \x01(\x0b\x32#.tflite_dynamic.UploadModelResponseH\x00\x12\x36\n\tinference\x18\x03 \x01(\x0b\x32!.tflite_dynamic.InferenceResponseH\x00\x12@\n\x0egetModelFormat\x18\x04 \x01(\x0b\x32&.tflite_dynamic.GetModelFormatResponseH\x00\x42\x11\n\x0ftflite_response\"\x17\n\x15GetModelFormatRequest\"J\n\x16GetModelFormatResponse\x12\x30\n\x0bmodelFormat\x18\x01 \x02(\x0b\x32\x1b.tflite_dynamic.ModelFormat\"\xbd\x01\n\x0bModelFormat\x12\x13\n\x0bmodelSha256\x18\x01 \x02(\x0c\x12\x11\n\tmodelSize\x18\x02 \x02(\x05\x12\x11\n\tarenaSize\x18\x03 \x02(\x05\x12\x38\n\x12inputTensorFormats\x18\x04 \x03(\x0b\x32\x1c.tflite_dynamic.TensorFormat\x12\x39\n\x13outputTensorFormats\x18\x05 \x03(\x0b\x32\x1c.tflite_dynamic.TensorFormat\"C\n\x0cTensorFormat\x12\x12\n\ndimensions\x18\x01 \x03(\x05\x12\x11\n\tvalueType\x18\x02 \x02(\t\x12\x0c\n\x04size\x18\x03 \x02(\x05\"#\n\x12UploadModelRequest\x12\r\n\x05model\x18\x01 \x02(\x0c\"\x15\n\x13UploadModelResponse\"!\n\x10InferenceRequest\x12\r\n\x05input\x18\x01 \x02(\x0c\"#\n\x11InferenceResponse\x12\x0e\n\x06output\x18\x01 \x02(\x0c'
)




_TFLITEREQUEST = _descriptor.Descriptor(
  name='TfliteRequest',
  full_name='tflite_dynamic.TfliteRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='uploadModel', full_name='tflite_dynamic.TfliteRequest.uploadModel', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='inference', full_name='tflite_dynamic.TfliteRequest.inference', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='getModelFormat', full_name='tflite_dynamic.TfliteRequest.getModelFormat', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='tflite_request', full_name='tflite_dynamic.TfliteRequest.tflite_request',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=41,
  serialized_end=253,
)


_TFLITERESPONSE = _descriptor.Descriptor(
  name='TfliteResponse',
  full_name='tflite_dynamic.TfliteResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='failure', full_name='tflite_dynamic.TfliteResponse.failure', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='uploadModel', full_name='tflite_dynamic.TfliteResponse.uploadModel', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='inference', full_name='tflite_dynamic.TfliteResponse.inference', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='getModelFormat', full_name='tflite_dynamic.TfliteResponse.getModelFormat', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='tflite_response', full_name='tflite_dynamic.TfliteResponse.tflite_response',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=256,
  serialized_end=492,
)


_GETMODELFORMATREQUEST = _descriptor.Descriptor(
  name='GetModelFormatRequest',
  full_name='tflite_dynamic.GetModelFormatRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=494,
  serialized_end=517,
)


_GETMODELFORMATRESPONSE = _descriptor.Descriptor(
  name='GetModelFormatResponse',
  full_name='tflite_dynamic.GetModelFormatResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='modelFormat', full_name='tflite_dynamic.GetModelFormatResponse.modelFormat', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=519,
  serialized_end=593,
)


_MODELFORMAT = _descriptor.Descriptor(
  name='ModelFormat',
  full_name='tflite_dynamic.ModelFormat',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='modelSha256', full_name='tflite_dynamic.ModelFormat.modelSha256', index=0,
      number=1, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='modelSize', full_name='tflite_dynamic.ModelFormat.modelSize', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='arenaSize', full_name='tflite_dynamic.ModelFormat.arenaSize', index=2,
      number=3, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='inputTensorFormats', full_name='tflite_dynamic.ModelFormat.inputTensorFormats', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='outputTensorFormats', full_name='tflite_dynamic.ModelFormat.outputTensorFormats', index=4,
      number=5, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=596,
  serialized_end=785,
)


_TENSORFORMAT = _descriptor.Descriptor(
  name='TensorFormat',
  full_name='tflite_dynamic.TensorFormat',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='dimensions', full_name='tflite_dynamic.TensorFormat.dimensions', index=0,
      number=1, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='valueType', full_name='tflite_dynamic.TensorFormat.valueType', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='size', full_name='tflite_dynamic.TensorFormat.size', index=2,
      number=3, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=787,
  serialized_end=854,
)


_UPLOADMODELREQUEST = _descriptor.Descriptor(
  name='UploadModelRequest',
  full_name='tflite_dynamic.UploadModelRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='model', full_name='tflite_dynamic.UploadModelRequest.model', index=0,
      number=1, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=856,
  serialized_end=891,
)


_UPLOADMODELRESPONSE = _descriptor.Descriptor(
  name='UploadModelResponse',
  full_name='tflite_dynamic.UploadModelResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=893,
  serialized_end=914,
)


_INFERENCEREQUEST = _descriptor.Descriptor(
  name='InferenceRequest',
  full_name='tflite_dynamic.InferenceRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='input', full_name='tflite_dynamic.InferenceRequest.input', index=0,
      number=1, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=916,
  serialized_end=949,
)


_INFERENCERESPONSE = _descriptor.Descriptor(
  name='InferenceResponse',
  full_name='tflite_dynamic.InferenceResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='output', full_name='tflite_dynamic.InferenceResponse.output', index=0,
      number=1, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=951,
  serialized_end=986,
)

_TFLITEREQUEST.fields_by_name['uploadModel'].message_type = _UPLOADMODELREQUEST
_TFLITEREQUEST.fields_by_name['inference'].message_type = _INFERENCEREQUEST
_TFLITEREQUEST.fields_by_name['getModelFormat'].message_type = _GETMODELFORMATREQUEST
_TFLITEREQUEST.oneofs_by_name['tflite_request'].fields.append(
  _TFLITEREQUEST.fields_by_name['uploadModel'])
_TFLITEREQUEST.fields_by_name['uploadModel'].containing_oneof = _TFLITEREQUEST.oneofs_by_name['tflite_request']
_TFLITEREQUEST.oneofs_by_name['tflite_request'].fields.append(
  _TFLITEREQUEST.fields_by_name['inference'])
_TFLITEREQUEST.fields_by_name['inference'].containing_oneof = _TFLITEREQUEST.oneofs_by_name['tflite_request']
_TFLITEREQUEST.oneofs_by_name['tflite_request'].fields.append(
  _TFLITEREQUEST.fields_by_name['getModelFormat'])
_TFLITEREQUEST.fields_by_name['getModelFormat'].containing_oneof = _TFLITEREQUEST.oneofs_by_name['tflite_request']
_TFLITERESPONSE.fields_by_name['uploadModel'].message_type = _UPLOADMODELRESPONSE
_TFLITERESPONSE.fields_by_name['inference'].message_type = _INFERENCERESPONSE
_TFLITERESPONSE.fields_by_name['getModelFormat'].message_type = _GETMODELFORMATRESPONSE
_TFLITERESPONSE.oneofs_by_name['tflite_response'].fields.append(
  _TFLITERESPONSE.fields_by_name['failure'])
_TFLITERESPONSE.fields_by_name['failure'].containing_oneof = _TFLITERESPONSE.oneofs_by_name['tflite_response']
_TFLITERESPONSE.oneofs_by_name['tflite_response'].fields.append(
  _TFLITERESPONSE.fields_by_name['uploadModel'])
_TFLITERESPONSE.fields_by_name['uploadModel'].containing_oneof = _TFLITERESPONSE.oneofs_by_name['tflite_response']
_TFLITERESPONSE.oneofs_by_name['tflite_response'].fields.append(
  _TFLITERESPONSE.fields_by_name['inference'])
_TFLITERESPONSE.fields_by_name['inference'].containing_oneof = _TFLITERESPONSE.oneofs_by_name['tflite_response']
_TFLITERESPONSE.oneofs_by_name['tflite_response'].fields.append(
  _TFLITERESPONSE.fields_by_name['getModelFormat'])
_TFLITERESPONSE.fields_by_name['getModelFormat'].containing_oneof = _TFLITERESPONSE.oneofs_by_name['tflite_response']
_GETMODELFORMATRESPONSE.fields_by_name['modelFormat'].message_type = _MODELFORMAT
_MODELFORMAT.fields_by_name['inputTensorFormats'].message_type = _TENSORFORMAT
_MODELFORMAT.fields_by_name['outputTensorFormats'].message_type = _TENSORFORMAT
DESCRIPTOR.message_types_by_name['TfliteRequest'] = _TFLITEREQUEST
DESCRIPTOR.message_types_by_name['TfliteResponse'] = _TFLITERESPONSE
DESCRIPTOR.message_types_by_name['GetModelFormatRequest'] = _GETMODELFORMATREQUEST
DESCRIPTOR.message_types_by_name['GetModelFormatResponse'] = _GETMODELFORMATRESPONSE
DESCRIPTOR.message_types_by_name['ModelFormat'] = _MODELFORMAT
DESCRIPTOR.message_types_by_name['TensorFormat'] = _TENSORFORMAT
DESCRIPTOR.message_types_by_name['UploadModelRequest'] = _UPLOADMODELREQUEST
DESCRIPTOR.message_types_by_name['UploadModelResponse'] = _UPLOADMODELRESPONSE
DESCRIPTOR.message_types_by_name['InferenceRequest'] = _INFERENCEREQUEST
DESCRIPTOR.message_types_by_name['InferenceResponse'] = _INFERENCERESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TfliteRequest = _reflection.GeneratedProtocolMessageType('TfliteRequest', (_message.Message,), {
  'DESCRIPTOR' : _TFLITEREQUEST,
  '__module__' : 'tflite_dynamic_pb2'
  # @@protoc_insertion_point(class_scope:tflite_dynamic.TfliteRequest)
  })
_sym_db.RegisterMessage(TfliteRequest)

TfliteResponse = _reflection.GeneratedProtocolMessageType('TfliteResponse', (_message.Message,), {
  'DESCRIPTOR' : _TFLITERESPONSE,
  '__module__' : 'tflite_dynamic_pb2'
  # @@protoc_insertion_point(class_scope:tflite_dynamic.TfliteResponse)
  })
_sym_db.RegisterMessage(TfliteResponse)

GetModelFormatRequest = _reflection.GeneratedProtocolMessageType('GetModelFormatRequest', (_message.Message,), {
  'DESCRIPTOR' : _GETMODELFORMATREQUEST,
  '__module__' : 'tflite_dynamic_pb2'
  # @@protoc_insertion_point(class_scope:tflite_dynamic.GetModelFormatRequest)
  })
_sym_db.RegisterMessage(GetModelFormatRequest)

GetModelFormatResponse = _reflection.GeneratedProtocolMessageType('GetModelFormatResponse', (_message.Message,), {
  'DESCRIPTOR' : _GETMODELFORMATRESPONSE,
  '__module__' : 'tflite_dynamic_pb2'
  # @@protoc_insertion_point(class_scope:tflite_dynamic.GetModelFormatResponse)
  })
_sym_db.RegisterMessage(GetModelFormatResponse)

ModelFormat = _reflection.GeneratedProtocolMessageType('ModelFormat', (_message.Message,), {
  'DESCRIPTOR' : _MODELFORMAT,
  '__module__' : 'tflite_dynamic_pb2'
  # @@protoc_insertion_point(class_scope:tflite_dynamic.ModelFormat)
  })
_sym_db.RegisterMessage(ModelFormat)

TensorFormat = _reflection.GeneratedProtocolMessageType('TensorFormat', (_message.Message,), {
  'DESCRIPTOR' : _TENSORFORMAT,
  '__module__' : 'tflite_dynamic_pb2'
  # @@protoc_insertion_point(class_scope:tflite_dynamic.TensorFormat)
  })
_sym_db.RegisterMessage(TensorFormat)

UploadModelRequest = _reflection.GeneratedProtocolMessageType('UploadModelRequest', (_message.Message,), {
  'DESCRIPTOR' : _UPLOADMODELREQUEST,
  '__module__' : 'tflite_dynamic_pb2'
  # @@protoc_insertion_point(class_scope:tflite_dynamic.UploadModelRequest)
  })
_sym_db.RegisterMessage(UploadModelRequest)

UploadModelResponse = _reflection.GeneratedProtocolMessageType('UploadModelResponse', (_message.Message,), {
  'DESCRIPTOR' : _UPLOADMODELRESPONSE,
  '__module__' : 'tflite_dynamic_pb2'
  # @@protoc_insertion_point(class_scope:tflite_dynamic.UploadModelResponse)
  })
_sym_db.RegisterMessage(UploadModelResponse)

InferenceRequest = _reflection.GeneratedProtocolMessageType('InferenceRequest', (_message.Message,), {
  'DESCRIPTOR' : _INFERENCEREQUEST,
  '__module__' : 'tflite_dynamic_pb2'
  # @@protoc_insertion_point(class_scope:tflite_dynamic.InferenceRequest)
  })
_sym_db.RegisterMessage(InferenceRequest)

InferenceResponse = _reflection.GeneratedProtocolMessageType('InferenceResponse', (_message.Message,), {
  'DESCRIPTOR' : _INFERENCERESPONSE,
  '__module__' : 'tflite_dynamic_pb2'
  # @@protoc_insertion_point(class_scope:tflite_dynamic.InferenceResponse)
  })
_sym_db.RegisterMessage(InferenceResponse)


# @@protoc_insertion_point(module_scope)
